config/routes.rb
Rails.application.routes.draw do
  resources :white_book_leads, only: [:index, :new, :create, :destroy]
  resources :newsletter_leads, only: [:index, :new, :create, :destroy]
  resources :criteria_leads, only: [:index, :new, :create, :destroy]
  resources :compatibility_leads, only: [:index, :new, :create, :destroy]
  resources :vip_leads, only: [:index, :new, :create, :destroy]
  get 'carts/show'
  resources :products, path: 'produits', only: [:index, :show] do
    collection do
      get :trailers, path: '/remorques'
      get :accessories, path: '/accessoires'
      get :maintenance, path: '/entretien'
      get :installations, path: '/installations'
      get :documents, path: '/services'
      get :luggage, path: '/remorques/bagageres/utilitaires'
      get :water, path: '/remorques/nautiques'
      get :animals, path: "/remorques/transport-d-animaux/vans"
      get :garden, path: '/remorques/espaces-verts/jardin'
      get :bin, path: '/remorques/bennes'
      get :moto, path: '/remorques/porte-moto'
      get :car, path: '/remorques/porte-voiture'
      get :truck, path: '/remorques/porte-engin'
      get :trail, path: '/remorques/plateaux'
      get :close, path: '/remorques/fourgons'
      get :market, path: '/remorques/magasins'

      get :rent, path: 'location/remorques'
      get :luggage_rent, path: 'location/remorques/bagageres/utilitaires'
      get :water_rent, path: 'location/remorques/nautiques'
      get :animals_rent, path: "location/remorques/transport-d-animaux/van"
      get :garden_rent, path: 'location/remorques/espaces-verts/jardin'
      get :bin_rent, path: 'location/remorques/bennes'
      get :moto_rent, path: 'location/remorques/porte-moto'
      get :car_rent, path: 'location/remorques/porte-voiture'
      get :truck_rent, path: 'location/remorques/porte-engin'
      get :trail_rent, path: 'location/remorques/plateaux'
      get :close_rent, path: 'location/remorques/fourgons'
      get :market_rent, path: 'location/remorques/magasins'


      get :wires, path: 'accessoires/equipement-electrique'
      get :lockers, path: 'accessoires/attelage'
      get :sticks, path: 'accessoires/essieux'
      get :wheels, path: 'accessoires/roues'
      get :suspensions, path: 'accessoires/suspensions'
      get :sheets, path: 'accessoires/baches'
      get :set, path: 'atelier/entretien/réglages'
      get :direction, path: 'atelier/entretien/direction'
      get :reinforcements, path: 'atelier/entretien/suspensions-renforts'
      get :stabilisation, path: 'atelier/entretien/aide-a-la-manoeuvre'
      get :wire_installation, path: 'atelier/installation/equipement-electrique'
      get :stick_installation, path: 'atelier/installation/essieux'
      get :reinforcements_installation, path: 'atelier/installation/suspensions-renforts'
      get :locker_installation, path: 'atelier/installation/attelage'
      get :direction_installation, path: 'atelier/installation/direction'
      get :stabilisation_installation, path: 'atelier/installation/aide-à-la-manoeuvre'
      get :plate, path: 'service/immatriculation'
      get :technical_control, path: 'service/controle-technique'
      get :insurrance, path: 'service/assurance'
      get :rent, path: 'service/location'
      get :service, path: 'services'
      get :trailers_permisb_casual_luggage, path: '/remorques/bagageres/usage-occasionnel/permisb'
      get :trailers_permisb_casual_water, path: '/remorques/nautiques/usage-occasionnel/permisb'
      get :trailers_permisb_casual_animal, path: '/remorques/tranport-d-animaux/usage-occasionnel/permisb'
      get :trailers_permisb_casual_garden, path: '/remorques/jardinage/usage-occasionnel/permisb'
      get :trailers_permisb_casual_moto, path: '/remorques/porte-moto/usage-occasionnel/permisb'
      get :trailers_permisb_casual_close, path: '/remorques/fourgon/usage-occasionnel/permisb'
    end
    resources :quotations, only: [:index, :new, :create ]
    resources :reservations, only: [:new, :create, :destroy]
  end
  get '/sitemap.xml' => 'sitemaps#index', defaults: { format: 'xml' }
  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unacceptable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  get 'pages/holidays'
  get 'pages/horses'
  get 'pages/constant_gardener'
  get 'pages/smart'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/best_use.rb
class BestUse < ApplicationRecord
  has_many :product_best_uses, dependent: :destroy
  has_many :products, through: :product_best_uses
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_products, dependent: :destroy
  has_many :products, through: :cart_products
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/criteria_lead.rb
class CriteriaLead < ApplicationRecord
  validates :email, format: { with:  /\A[^@\s]+@[^@\s]+\z/}, presence: true
end

app/models/document.rb
class Document < ApplicationRecord
  has_many :products
end

app/models/newsletter_lead.rb
class NewsletterLead < ApplicationRecord
  validates :email, format: { with:  /\A[^@\s]+@[^@\s]+\z/}, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :photo
  belongs_to :category
  belongs_to :subcategory
  belongs_to :brand
  belongs_to :document
  belongs_to :usage
  belongs_to :wheel_size
  belongs_to :wheel_axle
  has_many :reservations, dependent: :destroy
  has_many :quotations, dependent: :destroy
  has_many :cart_products, dependent: :destroy
  has_many :carts, through: :cart_products
  has_many :product_best_uses, dependent: :destroy
  has_many :best_uses, through: :product_best_uses
  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :name, :price, :rent, :second_hand, :max_load_weight ],
    associated_against: {
      category: [ :name],
      document: [ :name],
      brand: [ :name],
      usage: [ :name],
      subcategory: [ :name]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/models/purpose.rb
class Purpose < ApplicationRecord
  has_many :quotations
end

app/models/quotation.rb
class Quotation < ApplicationRecord
  belongs_to :product
  belongs_to :title
  belongs_to :purpose
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  validates :name, presence: true
  validates :surname, presence: true
  validates :mail, format: { with:  /\A[^@\s]+@[^@\s]+\z/}, presence: true
  belongs_to :product
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  has_many :products
end

app/models/title.rb
class Title < ApplicationRecord
  has_many :vip_leads
  has_many :quotations
end

app/models/usage.rb
class Usage < ApplicationRecord
  has_many :products
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :carts
  after_create :send_welcome_email

  private

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end
end

app/models/vip_lead.rb
class VipLead < ApplicationRecord
  validates :email, format: { with:  /\A[^@\s]+@[^@\s]+\z/}, presence: true
  belongs_to :title
  validates :name, presence: true
  validates :surname, presence: true
end

app/models/wheel_axle.rb
class WheelAxle < ApplicationRecord
  has_many :products
end

app/models/wheel_size.rb
class WheelSize < ApplicationRecord
  has_many :products
end

app/models/white_book_lead.rb
class WhiteBookLead < ApplicationRecord
  validates :email, format: { with:  /\A[^@\s]+@[^@\s]+\z/}, presence: true
end

app/views/index/create.html.erb
<h1>Index#create</h1>
<p>Find me in app/views/index/create.html.erb</p>

app/views/index/destroy.html.erb
<h1>Index#destroy</h1>
<p>Find me in app/views/index/destroy.html.erb</p>

app/views/index/new.html.erb
<h1>Index#new</h1>
<p>Find me in app/views/index/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="description" content="#{meta_description}">


    <meta property="og:title" content="#{meta_title}">
    <meta property="og:type" content="website">
    <meta property="og:url" content="#{request.original_url}">
    <meta property="og:image" content="#{meta_image}">
    <meta property="og:description" content="#{meta_description}">
    <meta property="og:site_name" content="#{meta_title}">
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-CNN80GLF83"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-CNN80GLF83');
    </script>
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/category_nav' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
    <%= render 'shared/footer' %>
    <%= render 'shared/sub-footer' %>
    <script>
      $(document).ready(function(){
        $("#informations-trigger").click(function(){
          $("#informations").toggle();
        });
      });
    </script>
    <script>
      $(document).ready(function(){
        $("#advice-trigger").click(function(){
          $("#advice").toggle();
        });
      });
    </script>
    <script>
      $(document).ready(function(){
        $("#description-trigger").click(function(){
          $("#description").toggle();
        });
      });
    </script>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="row">
      <%= image_tag 'https://res.cloudinary.com/da2krghvd/image/upload/c_crop,g_center,h_120,w_250/v1643388825/Portfolio/soumat_logo_blanc.png', class: 'footer-brand'%>
    </div>
    <div class="row">
      <div class="col-lg-6 mx-auto">
        <%= image_tag 'https://res.cloudinary.com/da2krghvd/image/upload/v1647006680/production/Capture_d_e%CC%81cran_2022-03-11_a%CC%80_14.50.20.png', class: 'img-fluid map' %>
      </div>
    </div>
    <div class="row main">
      <div class="col-sm-6 col-md-3 col-lg-3">
        <div class="item">
          <h3>Les Horaires</h3>
          <div class="row">
            <div class="col-lg-6">
              <p>Du lundi au vendredi</p>
            </div>
            <div class="col-lg-6">
              <p><span class='colored-brand'>8h30 - 12h30</span></p>
              <p><span class='colored-brand'>14h - 17h </span></p>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6">
              <p>Samedi</p>
            </div>
            <div class="col-lg-6">
              <p><span class='colored-brand'>8h30 - 12h30</span></p>
              <p><span class='colored-brand'>14h - 18h </span></p>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6">
              <p>Dimanche</p>
            </div>
            <div class="col-lg-6">
              <p><span class='colored-brand'>Fermeture</span></p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-6 col-md-3">
        <div class="item">
          <h3>Activités</h3>
          <p>Vente de remorques et accessoires</p>
          <p>Location de remorques</p>
          <p>Atelier d'entretien et installation</p>
          <p>Services réglementaires</p>
        </div>
      </div>
      <div class="col-md-3 item text">
        <h3>Soumat Remorques</h3>
        <p>200 avenue Gén Leclerc, 33600 Pessac, FRANCE</p>
        <p><i class="fas fa-phone"></i> <span class="colored">05 56 36 01 01</span></p>
        <p>45 années d'expertise à votre service.</p>
      </div>
      <div class="col-md-3 item text">
        <h3>Suivez-nous</h3>
        <%= link_to 'https://www.facebook.com/SoumatRemorques/', target: "_blank" do  %>
          <p><i class="fab fa-facebook-square colored"></i> FACEBOOK</p>
        <% end %>
        <p><i class="fab fa-facebook-messenger colored"></i> FACEBOOK MESSENGER</p>
        <p><i class="fab fa-instagram colored"></i> INSTAGRAM</p>
      </div>
      <div class="col item social"><a href="#"><i class="icon ion-social-facebook"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-instagram"></i></a>
      </div>
    </div>
    <p class="copyright">Soumat Remorques© 2022</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container">
    <div class="row">
      <div class="col-6 col-sm-9 col-md-2 col-lg-3">
        <%= link_to root_path, class: "navbar-brand" do %>
          <%= image_tag 'https://res.cloudinary.com/da2krghvd/image/upload/c_crop,g_center,h_120,w_250/v1643388825/Portfolio/soumat_logo_blanc.png' %>
        <% end %>
      </div>

      <div class="col-2 col-sm-2 col-md-2 col-lg-6 d-none d-lg-block">
        <%= form_tag(products_path, method: :get) do %>
          <%= text_field_tag :search, nil, class: "form-control string required", autocomplete: 'off'%>
        <% end %>
      </div>

      <div class="col-6 col-sm-3 col-md-10 col-lg-3">
        <% if user_signed_in? %>
          <div class="user-area">
            <i class="fas fa-info-circle" data-bs-toggle="modal" data-bs-target="#conseil"></i>
            <i class="fas fa-heart"></i>
            <%= image_tag "https://res.cloudinary.com/da2krghvd/image/upload/c_fill,g_face,h_2440,w_2440/v1642098043/Portfolio/Avatar_noir.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </div>
        <% else %>
          <div class="user-area">
            <i class="fas fa-info-circle" data-bs-toggle="modal" data-bs-target="#conseil"></i>
            <i class="fas fa-heart"></i>
            <%= link_to new_user_session_path do %>
              <p class= "top-login">Mon</p>
              <p class= "low-login">Compte</p>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</nav>

<!-- Modal -->
<div class="modal fade" id="conseil" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Les conseils de soumat</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Saviez-vous qu'il existe <strong>différents types de remorques? </strong> Les remorques pour voyager, embarquer une moto ou transporter des gravats n'affichent pas nécessairement des caractéristiques techniques équivalentes. <em></em>De nombreux critères tels que les dimensions, le poids, les capacités de chargement ou encore le système de freinage doivent être pris en compte.
        Pour vous aider, voici une sélection de modèles de remorques répartis par catégorie d'usage.
        Sachez également qu'acquérir une remorque suppose de respecter une réglementation stricte. Par exemple, une remorque dont le poids total autorisé en charge (PTAC) est supérieur à 500 kg doit posséder sa propre carte grise. Pour certains modèles très imposants, le conducteur devra suivre une formation appelée « B96 ». Prenez donc le temps de bien vous renseigner avant de faire votre choix !
        <br>
        <h5>la remorque bagagère</h5>
        <%= image_tag 'https://res.cloudinary.com/da2krghvd/image/upload/v1643909610/development/470cbabdm1u53hmxngc2vx0frn7n.png', height: 100, width: 150, crop: :fill %><br>
        Vous cherchez une remorque suffisamment volumineuse pour transporter vos bagages ou quelques matériaux ? La remorque bagagère est le modèle qu’il vous faut. À la fois pratique, compact et assez simple à manipuler, ce type de remorque se distingue par sa facilité de chargement ainsi que par sa légèreté. Bref, c’est la remorque idéale pour les amateurs de voyages, de bricolage ou de jardinage.
        <br>
        <h5>la remorque moto simple rail</h5>
        <%= image_tag 'https://res.cloudinary.com/da2krghvd/image/upload/v1646744986/development/shopping.webp', height: 100, width: 150, crop: :fill %>
        <br>
        Attelée à votre voiture, cette remorque vous permet de transporter une ou plusieurs motos (simple ou double rail). Le chargement s’effectue au moyen d’une rampe que le conducteur utilise pour monter sa moto sur la remorque avant de l’attacher solidement. Selon les modèles, le pilote peut même monter son véhicule sur la remorque en restant sur la moto ! Parfait pour emporter sa moto à l’autre bout de la France !
        <br>
        <h5>La remorque fourgon ou bâchée</h5>
        <%= image_tag 'https://res.cloudinary.com/da2krghvd/image/upload/v1643910548/development/0kv8cj1o7985ii11uwz9do5akran.png', height: 100, width: 150, crop: :fill %>
        <br>
        La remorque fourgon est composée de cloisons bâchées ou rigides. Ce système permet de protéger totalement les marchandises transportées. La majorité des modèles sont équipés d’un hayon de chargement ou d’un pont basculant. À savoir que certaines remorques fourgons haut de gamme sont également dotées d’une porte d’accès latérale...
        <br>
        <h5>La remorque plateau</h5>
        <%= image_tag 'https://res.cloudinary.com/da2krghvd/image/upload/v1643910381/development/yqkl5piiotwzx9xj1u34q20kgjsp.png', height: 100, width: 150, crop: :fill %>
        <br>
        Ultra polyvalentes, les remorques plateau permettent de transporter de nombreuses marchandises volumineuses : déchets verts, cartons, matériaux… Bref, c’est un peu la remorque à tout faire ! Pour le chargement, certains modèles sont basculants tandis que d’autres sont équipés de rails. Il vous suffit alors d’un simple diable pour monter vos marchandises.
        <br>
        <h5>La remorque utilitaire espaces verts</h5>
        <%= image_tag 'https://res.cloudinary.com/da2krghvd/image/upload/v1643910418/development/osgzg0qsm71enksa7lm2q949fysj.png', height: 100, width: 150, crop: :fill %>
        <br>
        À la différence de la remorque bagagère qui reste relativement basse, la remorque spécialement conçue pour transporter les déchets verts est rehaussée d’un grillage. Le but ? Éviter la dissémination des végétaux et autres gravats sur la route et décupler les capacités de chargement. Ce type de remorque utilitaire convient parfaitement aux jardiniers et aux bricoleurs qui vont régulièrement à la déchetterie.
        <br>
        <strong>Quelle remorque puis-je tirer avec ma voiture ?</strong>
        <br>
        En France, les détenteurs du permis B peuvent légalement tracter une remorque dont le poids total autorisé en charge (PTAC) n'excède pas 750 kg. Au-delà, le permis sera également suffisant si les PTAC de la voiture et de la remorque additionnés sont inférieurs à 3 500 kg. Astuce : le PTAC de votre véhicule est indiqué sur votre carte grise (mention F2). Si la somme des PTAC est comprise entre 3 500 et 4 250 kg, <span class='colored'>vous allez devoir suivre la formation dite « B96 » qui dure 7 heures.</span> Pour les PTAC voiture et remorque supérieurs à 4 250 kg, le permis BE est obligatoire.
        <br>
        <strong>Quid de l'assurance ?</strong>
        <br>
        Là encore, le PTAC de la remorque est déterminant ! Si celui-ci est inférieur à 750 kg, votre assurance voiture couvre probablement votre remorque. Mais, pour éviter toute mauvaise surprise, il convient toutefois de s'en assurer avant de prendre la route ! Pour les modèles dont le PTAC est supérieur à 750 kg, il est nécessaire de souscrire un contrat d'assurance spécifique. À noter également qu'une remorque de ce poids doit aussi passer le contrôle technique avant mise en circulation, puis tous les deux ans.
        <br>
        <strong>Comment bien attacher ma remorque ?</strong>
        <br>
        Pour tracter votre future remorque, votre voiture doit nécessairement être équipée d'un système d'attelage complet. Pour rappel, un attelage se compose :

        <em>d'une boule ou rotule </em>: c'est l'élément d'accroche de la remorque au véhicule ;
        <em>d'une ferrure </em>: il s'agit de la barre fixée sur les points d'ancrage du châssis de votre voiture ;
        <em>d'un faisceau électrique </em>: il permet le raccordement électrique de la remorque et, par conséquent, le fonctionnement des feux et autres fonctionnalités électriques du modèle.

        Pour utiliser une remorque en toute sécurité, il est essentiel de savoir correctement d'atteler. Pour ce faire, vous devez soigneusement aligner votre remorque à votre véhicule de manière à faciliter l'attache. Pour cela, le conducteur doit reculer sa voiture lentement jusqu'à s'approcher le plus près possible de la remorque. C'est à cette étape que vous devez positionner le bras d'attelage de votre remorque au-dessus de la boule et le descendre jusqu'à ce que l'enclenchement entre les deux éléments soit correctement effectué. Une fois la remarque attelée solidement, la roue jockey peut être relevée ou retirée. S'il s'agit d'une remorque freinée, le frein de parking doit être déverrouillé. Branchez maintenant le faisceau électrique à votre véhicule et <span class='colored'>contrôlez le bon fonctionnement des feux. Avant de prendre la route</span>, vous devez également installer soit l'attache secondaire pour une remorque non freinée, soit le câble de sécurité pour une remorque freinée.
        <br>
        <strong>Où trouver une remorque adaptée à ma voiture ?</strong>
        <br>
        Pour acheter un modèle de remorque qui conviendra à votre véhicule, plusieurs solutions s'offrent à vous.
        <div class="row">
          <div class="col-lg-8 mx-auto">
            <%= link_to 'https://eboutique.westfalia-automotive.com/fr-fr', target: '_blank' do %>
              <div class="btn btn-flat center">Vérifiez nos compatibilités véhicules</div>
            <% end %>
          </div>
        </div>
        <br>
        <strong>Conseils pour conduire une remorque</strong>
        <br>
        La conduite d'une remorque nécessite le respect de certaines mesures de sécurité. Même les modèles les plus compacts peuvent s'avérer compliqués à manipuler lorsque l'on débute. Voici quelques conseils pour assurer votre sécurité et celle des autres :

        contrôler le matériel avant de démarrer : freins, pression des pneus, châssis de la remorque, fonctionnement des feux… ;
        bien répartir le chargement pour éviter les déséquilibres ;
        éviter les surcharges ;
        vérifier l’arrimage du chargement ;
        être attentif pendant les manœuvres, surtout en marche arrière ;
        anticiper la longueur de la remorque avant de doubler un autre véhicule ;
        réduire sa vitesse dans les descentes, les routes étroites ou en cas de trafic dense…
      </div>
    </div>
  </div>
</div>

app/views/shared/_slogan.html.erb
<div class="slogan d-none d-lg-block" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/da2krghvd/image/upload/a_90/v1644137051/nick-nice-gPm8h3DS1s4-unsplash_d9xsfh.jpg);">
  <div class="container welcome">
    <h1>Bienvenue Chez Soumat</h1>
  </div>
</div>

app/views/shared/_sub-footer.html.erb
<footer class= "sub-footer d-block d-lg-none">
  <div class="container">
    <div class="row">
      <div class="col-2 mx-auto">
        <%= link_to trailers_products_path do %>
          <div class="bbox">
            <i class="fas fa-handshake"></i>
          </div>
          <p class='sub-footer-link'>Ventes</p>
        <% end %>
      </div>
      <div class="col-2 mx-auto">
        <%= link_to rent_products_path do %>
          <div class="bbox">
            <i class="fas fa-caravan"></i>
          </div>
          <p class='sub-footer-link'>Locations</p>
        <% end %>
      </div>
      <div class="col-2 mx-auto">
        <%= link_to maintenance_products_path do %>
          <div class="bbox">
            <i class="fas fa-tools"></i>
          </div>
          <p class='sub-footer-link'>Atelier</p>
        <% end %>
      </div>
      <div class="col-2 mx-auto">
        <%= link_to accessories_products_path do %>
          <div class="bbox">
            <i class="fas fa-cogs"></i>
          </div>
          <p class='sub-footer-link'>Pièces</p>
        <% end %>
      </div>
      <div class="col-2 mx-auto">
        <%= link_to documents_products_path do %>
          <div class="bbox">
            <i class="fas fa-car"></i>
          </div>
          <p class='sub-footer-link'>Roulez</p>
        <% end %>
      </div>
    </div>
  </div>
</footer>